updated jenkinsfile

diff --git a/src/ui/Jenkinsfile b/src/ui/Jenkinsfile
--- a/src/ui/Jenkinsfile
+++ b/src/ui/Jenkinsfile
@@ -156,25 +156,24 @@ pipeline {
                     }
                 }
             }
-        }
-    }
-    
-    post {
-        always {
-            echo 'Cleaning up...'
-            sh """
-                docker rmi zohaibwarraich/retail-store-ui-service:${BUILD_NUMBER} || true
-            """
-            cleanWs()
-        }
-        success {
-            echo 'Pipeline completed successfully!'
-            slackSend channel: "retail-store-sample-aws", message: "Build Success: ${env.JOB_NAME} \nBuild Number: ${env.BUILD_NUMBER} \nYou can find the Code quality report, Dependency Check report, Trivy report here: ${env.BUILD_URL}"
-        }
-        failure {
-            echo 'Pipeline failed!'
-            slackSend channel: "retail-store-sample-aws", message: "Build Failed: ${env.JOB_NAME} \nBuild Number: ${env.BUILD_NUMBER} \nYou can find the Code quality report, Dependency Check report, Trivy report here: ${env.BUILD_URL}"
+            
+            post {
+                always {
+                    echo 'Cleaning up...'
+                    sh """
+                        docker rmi zohaibwarraich/retail-store-ui-service:${BUILD_NUMBER} || true
+                    """
+                    cleanWs()
+                }
+                success {
+                    echo 'Pipeline completed successfully!'
+                    slackSend channel: "retail-store-sample-aws", message: "Build Success: ${env.JOB_NAME} \nBuild Number: ${env.BUILD_NUMBER} \nYou can find the Code quality report, Dependency Check report, Trivy report here: ${env.BUILD_URL}"
+                }
+                failure {
+                    echo 'Pipeline failed!'
+                    slackSend channel: "retail-store-sample-aws", message: "Build Failed: ${env.JOB_NAME} \nBuild Number: ${env.BUILD_NUMBER} \nYou can find the Code quality report, Dependency Check report, Trivy report here: ${env.BUILD_URL}"
+                }
+            }
         }
     }
 }
-
